# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish menu

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run setup.py and build html
      run: |
        python setup.py develop
        python piatto.py docs/menu.csv docs/index.html
    - name: Run setup.py and build html
      run: |
        python setup.py develop
        python piatto.py docs/menu.csv docs/index.html
    - name: Checkout Pages branch
      uses: actions/checkout@v2
      with:
        repository: gogl92/SaboresDeAsia
        path: pages
    - name: Copy the files to the pages branch
      run: |
        \cp docs/index.html pages/index.html
        \cp docs/menu.csv pages/menu.csv
    - name: checkout
    - uses: actions/checkout@master
      with:
        ref: pages
    - name: build
      uses: github-actions-x/hugo@master
    - name: push
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'pages'
        commit-message: 'Updating pages 🌏'
        force-add: 'true'
        files: pages/index.html pages/menu.csv
